name: WorldWarp
version: "B2"
api: [4.0.0]
author: HWABAEG
main: WorldWarp\WorldWarp

commands:
  worldwarp:
   permission: worldwarp.true
   description: worldwarpcommand

permissions:
  worldwarp.true:
    default: true
